server:
  port: 9094

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb
      host: localhost
      port: 27017
      database: orderdb


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${random.uuid}